name: Unified Dogfooding scans
on:
  schedule:
    - cron: 0 4 * * * # Run the workflow every day at 04:00 UTC
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: github-ubuntu-latest-s
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: SonarSource_ci-github-actions
          primary_platform: SQC-EU
          shadow1_project_key: SonarSource_ci-github-actions
          shadow1_platform: Next
          shadow2_project_key: SonarSource_ci-github-actions
          shadow2_platform: SQC-US
